### ISSUE TITLE
Feedback from in-class dashboard reviews

### ISSUE THREAD

**Issue by stannam** [STAT547-UBC-2019-20/Group10#48]
Overall
- ~~Bigger text size~~

MAP tab
1. ~~The meaning of by_date and all is not obvious. Give some explanations about them.~~
2. ~~By_date ==> By date (consider removing the underbar)~~
3. ~~Fire can be better represented with the color red(Skipped as hard to change color)~~
4. ~~Put a static map of Australia under the plot (separate issue. Yulia will give us a hand)~~
5. ~~Consider radial buttons rather than slider (as the map does not plot a period between two dates)(Did as range slider)~~

ANALYSIS tab
1. ~~Provide explanations about variables of choice (what does scan/track/frp .. mean?)~~
2. ~~different colors for the effect size by independent variable~~ (dismissed)
3. ~~is_day 0 and 1 does not make sense on the legend~~ 
4. ~~when 'all' selected on the effect size plot, the y-axis title is just gone.~~

**Comment by luckymeng7** [comment]
Other Feedback:

General
- The user has to install library 'effect' and 'mitools' before running the app.R

Map tab:
- Add the points to actual map

Analysis tab:
- More expatriation on data, especially track and scan
- For effect size plot, when 'all' selected, the y-axis disappear 
- For legend is_day, it would be nice to change it as day and night instead of 1 and 0

Good job Stanley! Can't appreciate more of your work!
